name: Build openvox-server

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag to build'
        required: true
      deb_platform_list:
        description: 'A comma-separated list of deb-based platforms to build for, excluding the architecture (e.g. ubuntu-24.04,debian-12). Do not include spaces. If not provided, will use the default list of platforms supported by OpenVox Server and DB.'
        required: false
        type: string
      rpm_platform_list:
        description: 'A comma-separated list of rpm-based platforms to build for, excluding the architecture (e.g. el-9,amazon-2023). Do not include spaces. If not provided, will use the default list of platforms supported by OpenVox Server and DB.'
        required: false
        type: string

jobs:
  build:
    uses: 'openvoxproject/shared-actions/.github/workflows/build_ezbake.yml@main'
    with:
      ref: ${{ inputs.ref }}
      deb_platform_list: ${{ inputs.deb_platform_list }}
      rpm_platform_list: ${{ inputs.rpm_platform_list }}
    secrets: inherit
